Maxime
MaximeRenoux/tp-proc-dev-logiciel pull request #9
Opened 2023-03-11 17:13 UTC by MaximeRenoux

2023-03-12 08:40 UTC, djodjo89 requested changes
quelques remarques : 
- il faut systématiquement faire des tests (pour le frontend ça implique d’au moins regarder à quoi ressemble le résultat dans un navigateur)
- dans le cadre du dev frontend il faut aussi aller voir la console : il y a une erreur dedans

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
il manque l’étiquette "Activité" ici

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <input type="checkbox" id="check_imc" name="IMC">
il manque l’étiquette "IMC" ici

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <input type="checkbox" id="check_mbasal" name="IMC">
il manque l’étiquette "Métabolisme basal ici", et l’attribut "name" devrait être modifié

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <input id="champ_poids" type="poids" placeholder="70">
il manque l’étiquette "Poids (kg)"

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <input id="champ_taille" type="taille" placeholder="175">
il manque l’étiquette "Taille (cm)"

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <input id="champ_age" type="age" placeholder="45">
il manque l’étiquette "Age"

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <div>
l’idée de mettre une balise `div` est bonne, mais il faudrait le faire pour chaque entrée/ligne du formulaire

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +           checked>
l’attribut `name` des champs radio doivent être identiques (ici ça pourrait être `name="sexe"`
il faudrait que l’un des deux champs radio soit marqué comme `unchecked` par défaut

2023-03-12 08:40 UTC, djodjo89 commented on src/index.html
> +  <!-- <section id="metabolisme_basal">
il vaut mieux éviter à tout prix de mettre des commentaires non utilisés sur la branche "main", si ce code n’est plus utile on peut le supprimer

2023-03-12 08:40 UTC, djodjo89 commented on src/index.js
> +            meta_bas = parseFloat( document.getElementById('affichage_metabolisme_basal').innerHTML.substring(0,  document.getElementById('affichage_metabolisme_basal').innerHTML.length -2 ))*238
(c’est valable pour toutes les modifications du fichier `index.js`) ça ne fait pas partie du périmètre de la tâche, s’il faut faire un ticket supplémentaire dessus on peut en discuter, mais pour le moment il vaut mieux s’en tenir au plan initial

2023-03-12 18:44 UTC, MaximeRenoux commented on src/index.html
Ca fait pas partie des labels qui sont dans un autre ticket?

2023-03-12 18:47 UTC, MaximeRenoux commented on src/index.html
> +           checked>
Je propose de laisser une liste déroulante je pense que c'est tout aussi bien et plus simple!

2023-03-12 19:19 UTC, djodjo89 commented on src/index.html
c’est vrai, j’avais oublié, désolé

2023-03-12 19:22 UTC, djodjo89 commented on src/index.html
> +           checked>
en soit je n’ai rien contre l’idée, mais je pense que pour ce sprint il est trop tard pour changer le moqup (surtout qu’il faudrait que toute l’équipe se remette d’accord)
donc pour le moment je pense qu’il vaut mieux se baser sur le moqup, qu’on pourra faire évoluer par la suite

2023-03-13 13:43 UTC, djodjo89 approved these changes

2023-03-13 13:43 UTC, merged